import { lazy, Suspense } from 'react';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import ProtectedRoute from './ProtectedRoute.jsx';
import AppShell from '../components/layout/AppShell.jsx';
import Spinner from '../components/ui/Spinner.jsx';

// SHARED FILE — owned by the lead agent only (see docs/DECISIONS.md "Parallel execution plan").
// Phase 1/2 agents do NOT edit this file directly; they report the routes/guards/pages they need
// wired here in their final summary and the lead applies the change.
//
// Real pages so far: Login/Signup (Agent D), the Items module's own route element (separate
// Items agent). Every other page below is a lightweight placeholder until Phase 2 (Agents E/F)
// land Dashboard/Browse/Search/Shares/Members/Activity/Settings/PublicShareView — swap each
// `lazy(...)` import for the real one as those files land; nothing else in this file changes.

const Login = lazy(() => import('../pages/auth/Login.jsx'));
const Signup = lazy(() => import('../pages/auth/Signup.jsx'));
const ForgotPassword = lazy(() => import('../pages/auth/ForgotPassword.jsx'));
const ResetPassword = lazy(() => import('../pages/auth/ResetPassword.jsx'));
const AcceptInvite = lazy(() => import('../pages/auth/AcceptInvite.jsx'));
const Onboarding = lazy(() => import('../pages/Onboarding.jsx'));
const ItemsRoutes = lazy(() => import('../pages/items/ItemsRoutes.jsx'));

const Dashboard = lazy(() => import('../pages/Dashboard.jsx'));
const Browse = lazy(() => import('../pages/Browse.jsx'));
const DocumentDetail = lazy(() => import('../pages/DocumentDetail.jsx'));
const PersonDocuments = lazy(() => import('../pages/PersonDocuments.jsx'));
const Search = lazy(() => import('../pages/Search.jsx'));
const Shares = lazy(() => import('../pages/Shares.jsx'));
const Members = lazy(() => import('../pages/Members.jsx'));
const Activity = lazy(() => import('../pages/Activity.jsx'));
const Bin = lazy(() => import('../pages/Bin.jsx'));
const Settings = lazy(() => import('../pages/Settings.jsx'));
const PlatformSettings = lazy(() => import('../pages/PlatformSettings.jsx'));
const PublicShare = lazy(() => import('../pages/PublicShare.jsx'));
const NotFound = lazy(() => import('../pages/NotFound.jsx'));

function PageFallback() {
  return (
    <div className="flex min-h-[50vh] items-center justify-center">
      <Spinner size="lg" />
    </div>
  );
}

function withSuspense(element) {
  return <Suspense fallback={<PageFallback />}>{element}</Suspense>;
}

const router = createBrowserRouter([
  { path: '/login', element: withSuspense(<Login />) },
  { path: '/signup', element: withSuspense(<Signup />) },
  { path: '/forgot-password', element: withSuspense(<ForgotPassword />) },
  { path: '/reset-password', element: withSuspense(<ResetPassword />) },
  { path: '/accept-invite', element: withSuspense(<AcceptInvite />) },
  { path: '/onboarding', element: withSuspense(<Onboarding />) },
  { path: '/s/:token', element: withSuspense(<PublicShare />) },

  {
    element: (
      <ProtectedRoute>
        <AppShell />
      </ProtectedRoute>
    ),
    children: [
      { index: true, element: withSuspense(<Dashboard />) },
      { path: 'browse/*', element: withSuspense(<Browse />) },
      { path: 'document/:id', element: withSuspense(<DocumentDetail />) },
      // Member-first home's person view: /people/<membershipId> or /people/shared.
      { path: 'people/:memberId', element: withSuspense(<PersonDocuments />) },
      { path: 'search', element: withSuspense(<Search />) },
      { path: 'shares/*', element: withSuspense(<Shares />) },
      { path: 'members', element: withSuspense(<Members />) },
      { path: 'activity', element: withSuspense(<Activity />) },
      { path: 'bin', element: withSuspense(<Bin />) },
      { path: 'settings/*', element: withSuspense(<Settings />) },
      { path: 'platform-settings', element: withSuspense(<PlatformSettings />) },
      { path: 'items/*', element: withSuspense(<ItemsRoutes />) },
    ],
  },

  { path: '*', element: withSuspense(<NotFound />) },
]);

export function AppRouter() {
  return <RouterProvider router={router} />;
}
