import { lazy, Suspense } from 'react';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import ProtectedRoute from './ProtectedRoute.jsx';
import AppShell from '../components/layout/AppShell.jsx';
import Spinner from '../components/ui/Spinner.jsx';

// SHARED FILE — owned by the lead agent only (see docs/DECISIONS.md "Parallel execution plan").
// Phase 1/2 agents do NOT edit this file directly; they report the routes/guards/pages they need
// wired here in their final summary and the lead applies the change.
//
// Real pages so far: Login/Signup (Agent D), the Items module's own route element (separate
// Items agent). Every other page below is a lightweight placeholder until Phase 2 (Agents E/F)
// land Dashboard/Browse/Search/Shares/Members/Activity/Settings/PublicShareView — swap each
// `lazy(...)` import for the real one as those files land; nothing else in this file changes.

const Login = lazy(() => import('../pages/auth/Login.jsx'));
const Signup = lazy(() => import('../pages/auth/Signup.jsx'));
const ForgotPassword = lazy(() => import('../pages/auth/ForgotPassword.jsx'));
const ResetPassword = lazy(() => import('../pages/auth/ResetPassword.jsx'));
const AcceptInvite = lazy(() => import('../pages/auth/AcceptInvite.jsx'));
const ItemsRoutes = lazy(() => import('../pages/items/ItemsRoutes.jsx'));

const Dashboard = lazy(() => import('../pages/Dashboard.jsx'));
const Shares = lazy(() => import('../pages/Shares.jsx'));
const Members = lazy(() => import('../pages/Members.jsx'));
const Activity = lazy(() => import('../pages/Activity.jsx'));
const Settings = lazy(() => import('../pages/Settings.jsx'));
const PublicShare = lazy(() => import('../pages/PublicShare.jsx'));

function Placeholder({ label }) {
  return (
    <div className="flex min-h-[50vh] items-center justify-center p-6 text-center">
      <p className="text-sm text-neutral-500 dark:text-neutral-400">{label} — coming soon.</p>
    </div>
  );
}

// Temporary stand-ins for pages still landing. Replace each with
// `lazy(() => import('../pages/Whatever.jsx'))` once that file exists.
const Browse = () => <Placeholder label="Browse" />;
const Search = () => <Placeholder label="Search" />;
const NotFound = () => <Placeholder label="Page not found" />;

function PageFallback() {
  return (
    <div className="flex min-h-[50vh] items-center justify-center">
      <Spinner size="lg" />
    </div>
  );
}

function withSuspense(element) {
  return <Suspense fallback={<PageFallback />}>{element}</Suspense>;
}

const router = createBrowserRouter([
  { path: '/login', element: withSuspense(<Login />) },
  { path: '/signup', element: withSuspense(<Signup />) },
  { path: '/forgot-password', element: withSuspense(<ForgotPassword />) },
  { path: '/reset-password', element: withSuspense(<ResetPassword />) },
  { path: '/accept-invite', element: withSuspense(<AcceptInvite />) },
  { path: '/s/:token', element: withSuspense(<PublicShare />) },

  {
    element: (
      <ProtectedRoute>
        <AppShell />
      </ProtectedRoute>
    ),
    children: [
      { index: true, element: withSuspense(<Dashboard />) },
      { path: 'browse/*', element: <Browse /> },
      { path: 'search', element: <Search /> },
      { path: 'shares/*', element: withSuspense(<Shares />) },
      { path: 'members', element: withSuspense(<Members />) },
      { path: 'activity', element: withSuspense(<Activity />) },
      { path: 'settings/*', element: withSuspense(<Settings />) },
      { path: 'items/*', element: withSuspense(<ItemsRoutes />) },
    ],
  },

  { path: '*', element: <NotFound /> },
]);

export function AppRouter() {
  return <RouterProvider router={router} />;
}
