import { createBrowserRouter, RouterProvider } from 'react-router-dom';

// SHARED FILE — owned by the lead agent only (see docs/DECISIONS.md "Parallel execution plan").
// Phase 1/2 agents do NOT edit this file directly; they report the routes/guards/pages they
// need wired here in their final summary and the lead applies the change. This keeps route
// wiring conflict-free while five agents touch the client tree at once.
//
// Placeholder route tree — replaced with the full tree (auth pages, protected AppShell layout,
// browse/document/share/admin pages, the public /s/:token page outside the app shell) once
// Phase 1 (Agent D: AppShell, AuthContext, route guards) and Phase 2 (Agents E/F: actual pages)
// land.
function Placeholder() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100dvh', fontFamily: 'Inter, sans-serif' }}>
      <p>Family Vault — scaffold running. Pages land as agents finish their modules.</p>
    </div>
  );
}

const router = createBrowserRouter([
  { path: '/', element: <Placeholder /> },
  { path: '*', element: <Placeholder /> },
]);

export function AppRouter() {
  return <RouterProvider router={router} />;
}
